name: lint
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  lint:
    name: lint with ruff
    runs-on: ubuntu-latest
    steps:
      - name: pull code
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: install packages
        run: |
          python3 -m pip install --upgrade pip
          pip3 install ruff
      - name: lint with ruff
        run:  |
          ruff check .
